import Head from "next/head";
import type { ReactElement } from "react";
import PublicLayout from "@cmpt/layout/public";
import ArenaRooms from "@cmpt/pages/arenaRooms";

function Arena() {
  return (
    <>
      <Head>
        <title>Today</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArenaRooms />
    </>
  );
}

Arena.getLayout = (page: ReactElement) => <PublicLayout>{page}</PublicLayout>;

export default Arena;
