import Head from "next/head";
import type { ReactElement } from "react";
import PublicLayout from "@cmpt/layout/public";
import TodaysChallenge from "@cmpt/pages/todaysChallenge";

function Challenge() {
  return (
    <>
      <Head>
        <title>Today</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodaysChallenge />
    </>
  );
}

Challenge.getLayout = (page: ReactElement) => (
  <PublicLayout>{page}</PublicLayout>
);

export default Challenge;
