import Head from "next/head";
import type { ReactElement } from "react";
import PublicLayout from "@cmpt/layout/public";
import Link from "next/link";

function Home() {
  return (
    <>
      <Head>
        <title>Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col items-center lg:mt-8">
        <h1 className="mx-2 text-center text-md mb-4 lg:my-4 lg:mx-0 lg:max-w-[50%] lg:text-2xl">
          Footballer Name Puzzle is an online game that tests your knowledge of
          the world&apos;s top footballers. Players must guess their names from
          the clues provided. With an intuitive interface and lots of levels to
          choose from, Footballer Name Puzzle is the ideal game for football
          fans and puzzle enthusiasts alike. You can find it online and start
          playing right away!
        </h1>
        <Link
          href={"/challenge"}
          className="btn btn-primary text-2xl text-center md:btn-wide"
        >
          Start
        </Link>
      </section>
    </>
  );
}

Home.getLayout = (page: ReactElement) => <PublicLayout>{page}</PublicLayout>;

export default Home;
