import Head from "next/head";
import type { ReactElement } from "react";
import PublicLayout from "@cmpt/layout/public";
import DifficultyButtons from "@cmpt/containers/difficultyButtons";

function PreLocalPlay() {
  return (
    <>
      <Head>
        <title>Play</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col justify-center items-center">
        <h1 className="my-4 text-xl font-bold md:text-3xl">Choose difficulty: </h1>
        <DifficultyButtons />
      </section>
    </>
  );
}

PreLocalPlay.getLayout = (page: ReactElement) => (
  <PublicLayout>{page}</PublicLayout>
);

export default PreLocalPlay;
