name = "football-wordle-api"
main = "src/index.ts"
compatibility_date = "2024-04-03"

kv_namespaces = [
  { binding = "PLAYERSKV", id = "4bb80b6f8a0b40248b2038adfc429519" }
]

d1_databases = [
  { binding = "ARENA_DB", database_name = "guessthefootballer", database_id = "76bfd738-4814-4804-83b0-dbf1356aff8a" }
]

[durable_objects]
bindings = [
  { name = "ARENA_ROOM_DO", class_name = "ArenaRoom" },
]

[triggers]
crons = ["0 0 * * *"]

[[migrations]]
tag = "v1"
new_classes = ["ArenaRoom"]

[vars]
WEB_URL = "https://api.guessthefootballer.com"
ORIGIN = "https://guessthefootballer.com"
ENVIRONMENT = "production"
PLAYERS_FILENAME = "players-1713077307.json"
