name = "football-wordle-api"
main = "src/index.ts"
compatibility_date = "2023-02-02"

kv_namespaces = [
  { binding = "PLAYERSKV", id = "<ignored>", preview_id = "<ignored>" }
]

[durable_objects]
bindings = [
  { name = "ARENA_ROOM_DO", class_name = "ArenaRoom" },
]

[build]
command = "node esbuild.js"

[miniflare]
kv_persist = true
durable_objects_persist = true

[triggers]
crons = ["0 0 * * *"]

[[migrations]]
tag = "v1"
new_classes = ["ArenaRoom"]

[env.production]
kv_namespaces = [
  { binding = "PLAYERSKV", id = "319677fc5b764528850e1b18d57f853c" }
]
